<p>TYÖKOKEMUS<br/>
12/2014 – 31.12.2015 Web Kehittäjä ( Futuvision & gbtimes oy )
Nettijärjestelmät ylläpidot ja kehitykset. Haku optimointi, sisällys
strategian kehitykset, analytiikka, UI, ja UX suunnittelut. NGINX
optimointi jotta sopii paras drupaliin. GIT ja SVN versiohalnita. DDoS
hyökkäyksen estäminen. Ruby perusteiden monitoroinnin ohjelmien ylläpito , ja
virtuaaliympäristöjen ylläpitö. Asiakastuki.</p>
<p>KOULUTUS<br/>
09/2007 - 06/2010 DI-tutkinto, ohjelmistot ja järjestelmät, Tampereen teknillinen yliopisto (120 op)
Pääaine: Ohjelmistotekniikka Sivuaine: web-ohjelmistojen kehittäminen<br/>
10/2000 - 07/2004 Tekniikan kandidaatti, Tietokonetek., Cyprus International University (144 op)
Pääaine: tietokonetekniikka Sivuaine: ohjelmointi ja verkostoituminen</p>
